name: CML
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/iterative/cml:0-docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        entrypoint: ["sh", "-c"]
        args:
          - |
            echo "## Report" > report.md
            git diff >> report.md
            cml-send-comment report.md
